version: "3.9"
services:
  timetracking-db:
    container_name: timetracking-db
    image: postgres:latest
    environment:
      POSTGRES_DB: timetracking
      POSTGRES_USER: timetracking
      POSTGRES_PASSWORD: ${DB_PW_TimeTracking}
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U timetracking'] # <<<---
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - timetracking-db:/var/lib/postgresql/data
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - backend
    restart: unless-stopped
      
  timetracking:
    image: timetracking:latest
    depends_on:
      timetracking-db:
        condition: service_healthy
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://timetracking:5432/timetracking?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: timetracking
      SPRING_DATASOURCE_PASSWORD: ${DB_PW_TimeTracking}
      KEYCLOAK_AUTH-SERVER-URL: https://${DOMAIN}/auth
      SERVER_USE_FORWARD_HEADERS: "true"
      SERVER_FORWARD_HEADERS_STRATEGY: FRAMEWORK
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

volumes:
  timetracking-db:

 # Networks to be created to facilitate communication between containers
networks:
  backend:

